name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      PUBLIC_URL_DB: ${{ secrets.PUBLIC_URL_DB }}
      PUBLIC_USER: ${{ secrets.PUBLIC_USER }}
      PUBLIC_PASSWORD: ${{ secrets.PUBLIC_PASSWORD }}
      EUREKA_SERVER: ${{ secrets.EUREKA_SERVER }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean package

      